# Generated by Django 3.2.19 on 2023-07-12 18:33

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rescentpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content',
            field=tinymce.models.HTMLField(default='Blog Content'),
        ),
    ]
