# Generated by Django 3.2.19 on 2023-07-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default='Accreal Sports', max_length=50),
        ),
    ]
